export const locationCardData = [
  {
    title: 'Беруни',
    metroName: 'Беруни',
    isMetro: true,
    deliveryTime: 35,
    address: 'пр-т проспект Беруни, 47',
    timeWork: 'Пн-Вс: 09:00 — 00:00',
    rating: 4.9,
  },
  {
    title: 'Буюк Ипак Йули',
    metroName: 'Буюк Ипак Йули (бывш. Максим Горький)',
    isMetro: true,
    deliveryTime: 34,
    address: 'пр-т проспект Беруни, 47',
    timeWork: 'Пн-Вс: 09:00 — 00:00',
    rating: 4.85,
  },
  {
    title: 'Корасу',
    address: 'ул. Хамроева, 25',
    deliveryTime: 34,
    isMetro: false,
    timeWork: 'Пн-Вс: 09:00 — 00:00',
    rating: 4.73,
  },
  {
    title: 'Лисунова',
    address: 'пр-т проспект Беруни, 47',
    isMetro: false,
    deliveryTime: 34,
    timeWork: 'Пн-Вс: 09:00 — 00:00',
    rating: 4.87,
  },
  {
    title: 'Новза',
    metroName: 'Новза',
    isMetro: true,
    deliveryTime: 34,
    address: 'пр-т проспект Беруни, 47',
    timeWork: 'Пн-Вс: 09:00 — 00:00',
    rating: 4.74,
  },
  {
    title: 'Новомосковская',
    address: 'ул. Кары-Ниязи, 61',
    isMetro: false,
    deliveryTime: 34,
    timeWork: 'Пн-Вс: 09:00 — 00:00',
    rating: 4.82,
  },
];
